//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperationOrderServiceClient.OperationOrdService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OperationOrdService.IOperationOrder", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IOperationOrder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationOrder/Initialize", ReplyAction="http://tempuri.org/IOperationOrder/InitializeResponse")]
        void Initialize(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationOrder/Initialize", ReplyAction="http://tempuri.org/IOperationOrder/InitializeResponse")]
        System.Threading.Tasks.Task InitializeAsync(int a);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IOperationOrder/Add", ReplyAction="http://tempuri.org/IOperationOrder/AddResponse")]
        int Add(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IOperationOrder/Add", ReplyAction="http://tempuri.org/IOperationOrder/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IOperationOrder/Multiply", ReplyAction="http://tempuri.org/IOperationOrder/MultiplyResponse")]
        int Multiply(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IOperationOrder/Multiply", ReplyAction="http://tempuri.org/IOperationOrder/MultiplyResponse")]
        System.Threading.Tasks.Task<int> MultiplyAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationOrder/AddTwo", ReplyAction="http://tempuri.org/IOperationOrder/AddTwoResponse")]
        int AddTwo(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationOrder/AddTwo", ReplyAction="http://tempuri.org/IOperationOrder/AddTwoResponse")]
        System.Threading.Tasks.Task<int> AddTwoAsync(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationOrder/MultiplyTwo", ReplyAction="http://tempuri.org/IOperationOrder/MultiplyTwoResponse")]
        int MultiplyTwo(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationOrder/MultiplyTwo", ReplyAction="http://tempuri.org/IOperationOrder/MultiplyTwoResponse")]
        System.Threading.Tasks.Task<int> MultiplyTwoAsync(int a);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOperationOrderChannel : OperationOrderServiceClient.OperationOrdService.IOperationOrder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperationOrderClient : System.ServiceModel.ClientBase<OperationOrderServiceClient.OperationOrdService.IOperationOrder>, OperationOrderServiceClient.OperationOrdService.IOperationOrder {
        
        public OperationOrderClient() {
        }
        
        public OperationOrderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperationOrderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperationOrderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperationOrderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Initialize(int a) {
            base.Channel.Initialize(a);
        }
        
        public System.Threading.Tasks.Task InitializeAsync(int a) {
            return base.Channel.InitializeAsync(a);
        }
        
        public int Add(int a, int b) {
            return base.Channel.Add(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int a, int b) {
            return base.Channel.AddAsync(a, b);
        }
        
        public int Multiply(int a, int b) {
            return base.Channel.Multiply(a, b);
        }
        
        public System.Threading.Tasks.Task<int> MultiplyAsync(int a, int b) {
            return base.Channel.MultiplyAsync(a, b);
        }
        
        public int AddTwo(int a) {
            return base.Channel.AddTwo(a);
        }
        
        public System.Threading.Tasks.Task<int> AddTwoAsync(int a) {
            return base.Channel.AddTwoAsync(a);
        }
        
        public int MultiplyTwo(int a) {
            return base.Channel.MultiplyTwo(a);
        }
        
        public System.Threading.Tasks.Task<int> MultiplyTwoAsync(int a) {
            return base.Channel.MultiplyTwoAsync(a);
        }
    }
}
